[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "22.21.0" }

[template]
  [template.environment]
    ASTRO_DB_REMOTE_URL = "Your Turso database URL"
    ASTRO_DB_APP_TOKEN = "Your Turso database app token"
    BETTER_AUTH_SECRET = "Your Better Auth secret (You get to choose this)"
    BETTER_AUTH_URL = "Your Better Auth URL (Your Netlify site URL)"

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true
